services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=news_db
      - DB_USER=news_user
      - DB_PASSWORD=password
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=news_db
      - POSTGRES_USER=news_user
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
